"""Kaggle entrypoint for the Expense Tracker ML master pipeline.

Typical notebook usage:
    !python /kaggle/working/expense-tracker/ml/kaggle_train.py

The standard three datasets are fetched automatically from Hugging Face using
`ml/config/datasets.yaml`, normalized, cached under /kaggle/working, and then
passed to the master pipeline.

Useful overrides:
    EXPENSE_ML_OUTPUT=/kaggle/working/expense-ml-runs
    EXPENSE_ML_DATA_CACHE=/kaggle/working/expense-ml-data
    EXPENSE_ML_CONFIG=/kaggle/working/kaggle_datasets.yaml
    EXPENSE_ML_FORCE_FETCH=1
    EXPENSE_ML_CPU_THREADS=auto
    EXPENSE_ML_DATALOADER_WORKERS=8
    EXPENSE_ML_BATCH_SIZE=32
    EXPENSE_ML_EVAL_BATCH_SIZE=64
    EXPENSE_ML_MIXED_PRECISION=auto
    EXPENSE_ML_NO_TRANSFORMER=1

Hugging Face authentication:
    Set HF_TOKEN in the environment, or attach a Kaggle Secret named
    `HF_TOKEN`. The secret is copied into the child training process without
    ever being printed.
"""
from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys

import pandas as pd


ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "src"))


def install_local_package() -> None:
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-e", str(ROOT)], check=True)


def print_code_provenance() -> None:
    """Print the exact repository commit and taxonomy loaded by this process."""
    repo = ROOT.parent
    try:
        commit = subprocess.check_output(
            ["git", "-C", str(repo), "rev-parse", "HEAD"],
            text=True,
            stderr=subprocess.STDOUT,
        ).strip()
    except subprocess.CalledProcessError as exc:
        commit = f"unavailable ({exc.output.strip()})"

    from expense_ml.data import taxonomy

    finee_mapping = taxonomy.SOURCE_LABEL_MAP.get("finee-india", {})
    print("ML repository commit:", commit)
    print("ML taxonomy module:", taxonomy.__file__)
    print("FinEE cashback mapping:", finee_mapping.get("cashback"))
    print("FinEE refund mapping:", finee_mapping.get("refund"))


def configure_huggingface_auth() -> bool:
    """Load HF_TOKEN from the environment or Kaggle Secrets."""
    token = os.getenv("HF_TOKEN")
    if token:
        os.environ["HF_TOKEN"] = token.strip()
        return bool(os.environ["HF_TOKEN"])

    try:
        from kaggle_secrets import UserSecretsClient

        token = UserSecretsClient().get_secret("HF_TOKEN")
    except Exception:
        return False

    if token:
        os.environ["HF_TOKEN"] = token.strip()
    return bool(os.environ.get("HF_TOKEN"))


def _load_yaml(path: Path) -> dict:
    import yaml

    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _prepared_data_needs_refresh(prepared: Path) -> bool:
    """Detect prepared data generated by the old pre-canonical-ID normalizer."""
    if not prepared.exists():
        return True
    try:
        from expense_ml.data.taxonomy import CANONICAL_CATEGORIES

        labels = pd.read_parquet(prepared, columns=["label"])["label"].dropna().astype(str)
        unexpected = set(labels) - set(CANONICAL_CATEGORIES)
        if unexpected:
            print("Prepared data contains stale/non-canonical labels; forcing dataset refresh:", sorted(unexpected)[:25])
            return True
    except Exception as exc:
        print(f"Prepared-data validation failed ({type(exc).__name__}); forcing dataset refresh.")
        return True
    return False


def fetch_standard_datasets(
    config_path: Path,
    cache_dir: Path,
    progress: bool = True,
    *,
    force: bool = False,
) -> Path:
    from expense_ml.data.fetch import fetch_configured_datasets
    from expense_ml.data.prepare import save_prepared

    raw = _load_yaml(config_path)
    datasets = raw.get("datasets", [])
    if not datasets:
        raise ValueError(f"No datasets configured in {config_path}.")

    frame, manifest = fetch_configured_datasets(
        datasets,
        cache_dir=cache_dir,
        progress=progress,
        force=force,
    )
    prepared = cache_dir / "transactions.parquet"
    save_prepared(frame, prepared)
    (cache_dir / "fetch_manifest.json").write_text(
        json.dumps(manifest, indent=2),
        encoding="utf-8",
    )
    print(json.dumps({"prepared": str(prepared), "datasets": manifest}, indent=2))
    return prepared


def main() -> None:
    install_local_package()
    print_code_provenance()
    from expense_ml.resources import configure_resources

    resource_info = configure_resources()
    print("ML resources:", json.dumps(resource_info, indent=2))

    hf_authenticated = configure_huggingface_auth()
    print(f"Hugging Face authentication: {'available' if hf_authenticated else 'not available'}")

    output = Path(os.getenv("EXPENSE_ML_OUTPUT", "/kaggle/working/expense-ml-runs"))
    cache_dir = Path(os.getenv("EXPENSE_ML_DATA_CACHE", "/kaggle/working/expense-ml-data"))
    config = Path(os.getenv("EXPENSE_ML_CONFIG", str(ROOT / "config" / "datasets.yaml")))
    prepared = Path(os.getenv("EXPENSE_ML_PREPARED", str(cache_dir / "transactions.parquet")))

    force_fetch = os.getenv("EXPENSE_ML_FORCE_FETCH") == "1"
    if _prepared_data_needs_refresh(prepared):
        force_fetch = True

    if force_fetch:
        prepared = fetch_standard_datasets(config, cache_dir, progress=True, force=True)

    from expense_ml.master_pipeline import main as pipeline_main

    argv = ["--config", str(config), "--prepared", str(prepared), "--output", str(output)]
    if os.getenv("EXPENSE_ML_NO_TRANSFORMER") == "1":
        argv.append("--no-transformer")

    old_argv = sys.argv
    try:
        sys.argv = [old_argv[0], *argv]
        pipeline_main()
    finally:
        sys.argv = old_argv


if __name__ == "__main__":
    main()
