package com.example.expensetracker.model;

import jakarta.persistence.*;

import java.util.List;

/**
 * JPA entity representing an expense category in the Expense Tracker application.
 *
 * <p>Categories are used to classify expenses (e.g., Food, Transport, Utilities).
 * They can be either:</p>
 * <ul>
 *   <li><strong>User-specific</strong> — created by a particular {@link User};
 *       the {@code user} field is non-null and the category is visible only to that user.</li>
 *   <li><strong>Global</strong> — system-provided categories where the {@code user} field
 *       is {@code null}, visible and usable by all users.</li>
 * </ul>
 *
 * <p>Extends {@link BaseEntity} to inherit automatic {@code createdAt}
 * and {@code updatedAt} audit timestamp fields.</p>
 *
 * @author Yogeshwaran
 * @version 1.0
 * @see BaseEntity
 * @see com.example.expensetracker.repository.CategoryRepository
 */
@Entity
@Table(name = "categories")
public class Category extends BaseEntity {

    /**
     * The unique identifier for this category, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The human-readable name of the category (e.g., "Food", "Transport", "Utilities").
     * Must not be null or empty. Uniqueness per user is enforced at the service layer.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The user who created and owns this category.
     * A {@code null} value indicates a global (system-level) category available to all users.
     * Fetched lazily to avoid unnecessary joins.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * The list of expenses associated with this category.
     * Mapped via the {@code category} field on {@link Expense}.
     * Fetched lazily to prevent unintended data loading.
     */
    @OneToMany(mappedBy = "category", fetch = FetchType.LAZY)
    private List<Expense> expenses;

    /**
     * Constructs an empty {@code Category}.
     * Required by JPA and for Jackson deserialisation.
     */
    public Category() {}

    /**
     * Returns the unique database identifier of this category.
     *
     * @return the category ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique database identifier of this category.
     *
     * @param id the category ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the human-readable name of this category.
     *
     * @return the category name (e.g., "Food", "Transport")
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the human-readable name of this category.
     *
     * @param name the category name to set; must not be blank
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the user who owns this category, or {@code null} for global categories.
     *
     * @return the owning {@link User}, or {@code null} if this is a global category
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the user who owns this category.
     * Pass {@code null} to mark this category as a global (system-level) category.
     *
     * @param user the owning user, or {@code null} for a global category
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Returns the list of expenses classified under this category.
     *
     * @return a list of associated {@link Expense} entities; may be empty
     */
    public List<Expense> getExpenses() {
        return expenses;
    }

    /**
     * Sets the list of expenses classified under this category.
     *
     * @param expenses the list of {@link Expense} entities to associate
     */
    public void setExpenses(List<Expense> expenses) {
        this.expenses = expenses;
    }
}
