package com.example.expensetracker.model;

import jakarta.persistence.*;
import lombok.*;

import java.util.List;

/**
 * JPA entity representing an expense category in the Expense Tracker application.
 *
 * <p>Categories are used to classify expenses (e.g., Food, Transport, Utilities).
 * They can be either:</p>
 * <ul>
 *   <li><strong>User-specific</strong> — created by a particular {@link User};
 *       the {@code user} field is non-null and the category is visible only to that user.</li>
 *   <li><strong>Global</strong> — system-provided categories where the {@code user} field
 *       is {@code null}, visible and usable by all users.</li>
 * </ul>
 *
 * <p>Extends {@link BaseEntity} to inherit automatic {@code createdAt}
 * and {@code updatedAt} audit timestamp fields.</p>
 *
 * @author Yogeshwaran
 * @version 1.0
 * @see BaseEntity
 * @see com.example.expensetracker.repository.CategoryRepository
 */
@Entity
@Table(
    name = "categories",
    uniqueConstraints = {
        @UniqueConstraint(name = "uk_category_user_name", columnNames = {"name", "user_id"})
    },
    indexes = {
        @Index(name = "idx_category_user_id", columnList = "user_id")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Category extends BaseEntity {

    /**
     * The unique identifier for this category, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The human-readable name of the category (e.g., "Food", "Transport", "Utilities").
     * Must not be null or empty. Uniqueness per user is enforced at the service layer.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The user who created and owns this category.
     * A {@code null} value indicates a global (system-level) category available to all users.
     * Fetched lazily to avoid unnecessary joins.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * The list of expenses associated with this category.
     * Mapped via the {@code category} field on {@link Expense}.
     * Fetched lazily to prevent unintended data loading.
     */
    @OneToMany(mappedBy = "category", fetch = FetchType.LAZY)
    private List<Expense> expenses;
}
