package com.example.expensetracker.model;

import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * JPA entity representing a single expense transaction recorded by a user.
 *
 * <p>An {@code Expense} captures the amount spent, an optional description,
 * the date of the transaction, and an optional category for classification.
 * Every expense must be owned by a {@link User}.</p>
 *
 * <p>Extends {@link BaseEntity} to inherit automatic {@code createdAt}
 * and {@code updatedAt} audit timestamp fields.</p>
 *
 * @author Yogeshwaran
 * @version 1.0
 * @see BaseEntity
 * @see User
 * @see Category
 * @see com.example.expensetracker.repository.ExpenseRepository
 */
@Entity
@Table(name = "expenses", indexes = {
    @Index(name = "idx_expense_user_date", columnList = "user_id, expense_date"),
    @Index(name = "idx_expense_user_cat", columnList = "user_id, category_id")
})
public class Expense extends BaseEntity {

    /**
     * The unique identifier for this expense record, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The monetary value of this expense.
     * Stored with a precision of 10 digits and scale of 2 decimal places.
     * Must not be null and must be a positive value.
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    /**
     * An optional short note or description for this expense
     * (e.g., "Lunch at office canteen", "Monthly electricity bill").
     * Maximum length is 255 characters.
     */
    @Column(length = 255)
    private String description;

    /**
     * The calendar date on which this expense was incurred.
     * Must not be null. Stored as a SQL {@code DATE} type (without time).
     */
    @Column(nullable = false)
    private LocalDate expenseDate;

    /**
     * The user who owns this expense record.
     * Fetched lazily to avoid unnecessary joins. Must not be null.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The category used to classify this expense (e.g., Food, Transport).
     * May be {@code null} if the expense is not categorised.
     * Fetched lazily to avoid unnecessary joins.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private Category category;

    @Column(name = "is_recurring")
    private Boolean isRecurring = false;

    /**
     * Constructs an empty {@code Expense}.
     * Required by JPA and for Jackson deserialisation.
     */
    public Expense() {}

    /**
     * Returns the unique database identifier of this expense.
     *
     * @return the expense ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique database identifier of this expense.
     *
     * @param id the expense ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the monetary amount of this expense.
     *
     * @return the expense amount
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * Sets the monetary amount of this expense.
     *
     * @param amount the expense amount to set; must be a positive non-null value
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * Returns the optional description or note for this expense.
     *
     * @return the expense description, or {@code null} if not provided
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the optional description or note for this expense.
     *
     * @param description the expense description to set; maximum 255 characters
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the date on which this expense was incurred.
     *
     * @return the expense date
     */
    public LocalDate getExpenseDate() {
        return expenseDate;
    }

    /**
     * Sets the date on which this expense was incurred.
     *
     * @param expenseDate the expense date to set; must not be {@code null}
     */
    public void setExpenseDate(LocalDate expenseDate) {
        this.expenseDate = expenseDate;
    }

    /**
     * Returns the user who owns this expense record.
     *
     * @return the owning {@link User}
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the user who owns this expense record.
     *
     * @param user the user to assign as the owner; must not be {@code null}
     */
    public void setUser(User user) {
        this.user = user;
    }

    /**
     * Returns the category used to classify this expense.
     *
     * @return the associated {@link Category}, or {@code null} if uncategorised
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the category used to classify this expense.
     *
     * @param category the {@link Category} to associate; may be {@code null}
     */
    public void setCategory(Category category) {
        this.category = category;
    }

    public LocalDate getDate() {
        return expenseDate;
    }

    public void setDate(LocalDate date) {
        this.expenseDate = date;
    }

    public boolean isRecurring() {
        return isRecurring != null && isRecurring;
    }

    public void setRecurring(boolean recurring) {
        this.isRecurring = recurring;
    }
}
