package com.example.expensetracker.model;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * JPA entity representing a single expense transaction recorded by a user.
 *
 * <p>An {@code Expense} captures the amount spent, an optional description,
 * the date of the transaction, and an optional category for classification.
 * Every expense must be owned by a {@link User}.</p>
 *
 * <p>Extends {@link BaseEntity} to inherit automatic {@code createdAt}
 * and {@code updatedAt} audit timestamp fields.</p>
 *
 * @author Yogeshwaran
 * @version 1.0
 * @see BaseEntity
 * @see User
 * @see Category
 * @see com.example.expensetracker.repository.ExpenseRepository
 */
@Entity
@Table(name = "expenses", indexes = {
    @Index(name = "idx_expense_user_date", columnList = "user_id, expense_date"),
    @Index(name = "idx_expense_user_cat", columnList = "user_id, category_id")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Expense extends BaseEntity {

    /**
     * The unique identifier for this expense record, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The monetary value of this expense.
     * Stored with a precision of 10 digits and scale of 2 decimal places.
     * Must not be null and must be a positive value.
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    /**
     * An optional short note or description for this expense
     * (e.g., "Lunch at office canteen", "Monthly electricity bill").
     * Maximum length is 255 characters.
     */
    @Column
    private String description;

    /**
     * The calendar date on which this expense was incurred.
     * Must not be null. Stored as a SQL {@code DATE} type (without time).
     */
    @Column(nullable = false)
    private LocalDate expenseDate;

    /**
     * The user who owns this expense record.
     * Fetched lazily to avoid unnecessary joins. Must not be null.
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * The category used to classify this expense (e.g., Food, Transport).
     * May be {@code null} if the expense is not categorised.
     * Fetched lazily to avoid unnecessary joins.\n     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private Category category;

    @Builder.Default
    @Column(name = "is_recurring")
    private Boolean isRecurring = false;

    public boolean isRecurring() {
        return Boolean.TRUE.equals(isRecurring);
    }

    public void setRecurring(boolean recurring) {
        this.isRecurring = recurring;
    }
}
