package com.example.expensetracker.model;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;

/**
 * JPA entity representing a recurring (subscription-style) expense template.
 *
 * <p>A {@code RecurringExpense} acts as a scheduled expense blueprint. When a user
 * registers a subscription (e.g., Netflix, gym membership), this entity stores the
 * recurrence details. The {@link com.example.expensetracker.service.RecurringExpenseScheduler}
 * runs daily and automatically creates concrete {@link Expense} records whenever
 * the {@code nextDueDate} is reached or passed.</p>
 *
 * @author Yogeshwaran
 * @version 1.0
 * @see com.example.expensetracker.service.RecurringExpenseScheduler
 * @see com.example.expensetracker.repository.RecurringExpenseRepository
 */
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RecurringExpense {

    /**
     * The unique identifier for this recurring expense record,
     * auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The monetary amount charged each time this recurring expense is due
     * (e.g., 499.00 for a monthly subscription).
     */
    private BigDecimal amount;

    /**
     * A short description of the recurring expense (e.g., "Netflix Subscription").
     * When the scheduler auto-creates an expense, it appends {@code " (Auto)"}
     * to this description.
     */
    private String description;

    /**
     * The recurrence interval for this expense (e.g., {@code "MONTHLY"}).
     */
    private String frequency;

    /** Number of days between occurrences when {@link #frequency} is CUSTOM. */
    private Integer intervalDays;

    /**
     * The date on which the next expense occurrence is due to be auto-created.
     * After processing, this is advanced by one month so the record self-renews.
     */
    private LocalDate nextDueDate;

    /**
     * The expense category associated with each auto-generated occurrence.
     * Stored as a foreign key ({@code category_id}) in the database.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private Category category;

    /**
     * The user who owns and is billed for this recurring expense.
     * Stored as a foreign key ({@code user_id}) in the database.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;

    public RecurringExpense(Long id, BigDecimal amount, String description,
                            String frequency, LocalDate nextDueDate,
                            Category category, User user) {
        this.id = id;
        this.amount = amount;
        this.description = description;
        this.frequency = frequency;
        this.nextDueDate = nextDueDate;
        this.category = category;
        this.user = user;
    }
}
