package com.example.expensetracker.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;

/**
 * JPA entity representing a registered user of the Expense Tracker application.
 *
 * <p>A {@code User} is the primary actor in the system. All expenses, categories,
 * and budgets are scoped to an individual user. Authentication is performed using
 * the user's email as the unique login identifier, with a BCrypt-encoded password.</p>
 *
 * <p>Account state is controlled by two flags:</p>
 * <ul>
 *   <li>{@code enabled} — must be {@code true} for the user to authenticate.</li>
 *   <li>{@code accountLocked} — if {@code true}, prevents login regardless of credentials.</li>
 * </ul>
 *
 * @author Yogeshwaran
 * @version 1.0
 * @see com.example.expensetracker.repository.UserRepository
 * @see com.example.expensetracker.security.CustomUserDetails
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    /**
     * The unique identifier for this user, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The full display name of the user (e.g., "Yogeshwaran R").
     * Used for personalised UI rendering in the frontend dashboard.
     * Must not be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The user's unique login handle (e.g., "yoge_26"), distinct from
     * {@link #name}. Nullable at the DB level so existing accounts created
     * before this field existed aren't broken by the schema update; new
     * registrations require and validate it at the DTO layer instead.
     */
    @Column(unique = true)
    private String username;

    /**
     * The user's unique email address, used as their login identifier.
     * Must not be null. Uniqueness is enforced at the database level.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The BCrypt-encoded password for the user's account.
     * The plain-text password is never stored; encoding is handled
     * by {@link com.example.expensetracker.service.impl.UserServiceImpl}.
     * Must not be null.
     */
    @Column(nullable = false)
    private String password;

    /**
     * The BCrypt-encoded 6-digit Security PIN used for instant password reset
     * and biometric recovery without relying on third-party email delivery.
     */
    @Column(name = "security_pin_hash")
    private String securityPinHash;

    /**
     * Failed consecutive Security PIN attempts counter (lockout threshold: 5).
     */
    @Builder.Default
    @Column(name = "failed_pin_attempts")
    private Integer failedPinAttempts = 0;

    /**
     * Timestamp until which Security PIN verification is temporarily locked.
     */
    @Column(name = "pin_locked_until")
    private LocalDateTime pinLockedUntil;

    /**
     * Indicates whether this user account is active.
     * Set to {@code true} automatically upon successful registration.
     * Spring Security checks this flag before granting authentication.
     */
    @Column(nullable = false)
    private boolean enabled;

    /**
     * Indicates whether this user account has been locked.
     * Set to {@code false} upon registration. If {@code true}, the user
     * cannot log in even with valid credentials.
     */
    @Column(nullable = false)
    private boolean accountLocked;

    /**
     * The ISO 4217 3-letter currency code representing the user's preferred
     * display currency (e.g. {@code "INR"}, {@code "USD"}, {@code "EUR"}).
     * Defaults to {@code "INR"}. Stored and returned in every auth response
     * so clients can format monetary values consistently across devices.
     */
    @Builder.Default
    @Column(nullable = false, length = 3)
    private String currency = "INR";

    /**
     * The list of all expense records owned by this user.
     * Mapped via the {@code user} field on {@link Expense}.
     * Fetched lazily to avoid unintended bulk loading.
     */
    @OneToMany(mappedBy = "user", fetch = FetchType.LAZY)
    private List<Expense> expenses;

    /**
     * Helper to verify if user has set a Security PIN.
     */
    public boolean hasSecurityPin() {
        return securityPinHash != null && !securityPinHash.isBlank();
    }

    public int getFailedPinAttempts() {
        return failedPinAttempts != null ? failedPinAttempts : 0;
    }

    public void setFailedPinAttempts(int failedPinAttempts) {
        this.failedPinAttempts = failedPinAttempts;
    }
}
