package com.example.expensetracker.model;

import jakarta.persistence.*;

import java.util.List;

/**
 * JPA entity representing a registered user of the Expense Tracker application.
 *
 * <p>A {@code User} is the primary actor in the system. All expenses, categories,
 * and budgets are scoped to an individual user. Authentication is performed using
 * the user's email as the unique login identifier, with a BCrypt-encoded password.</p>
 *
 * <p>Account state is controlled by two flags:</p>
 * <ul>
 *   <li>{@code enabled} — must be {@code true} for the user to authenticate.</li>
 *   <li>{@code accountLocked} — if {@code true}, prevents login regardless of credentials.</li>
 * </ul>
 *
 * @author Yogeshwaran
 * @version 1.0
 * @see com.example.expensetracker.repository.UserRepository
 * @see com.example.expensetracker.security.CustomUserDetails
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * The unique identifier for this user, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The full display name of the user (e.g., "Yogeshwaran R").
     * Used for personalised UI rendering in the frontend dashboard.
     * Must not be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * The user's unique email address, used as their login identifier.
     * Must not be null. Uniqueness is enforced at the database level.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The BCrypt-encoded password for the user's account.
     * The plain-text password is never stored; encoding is handled
     * by {@link com.example.expensetracker.service.impl.UserServiceImpl}.
     * Must not be null.
     */
    @Column(nullable = false)
    private String password;

    /**
     * Indicates whether this user account is active.
     * Set to {@code true} automatically upon successful registration.
     * Spring Security checks this flag before granting authentication.
     */
    @Column(nullable = false)
    private boolean enabled;

    /**
     * Indicates whether this user account has been locked.
     * Set to {@code false} upon registration. If {@code true}, the user
     * cannot log in even with valid credentials.
     */
    @Column(nullable = false)
    private boolean accountLocked;

    /**
     * The list of all expense records owned by this user.
     * Mapped via the {@code user} field on {@link Expense}.
     * Fetched lazily to avoid unintended bulk loading.
     */
    @OneToMany(mappedBy = "user", fetch = FetchType.LAZY)
    private List<Expense> expenses;

    /**
     * Constructs an empty {@code User}.
     * Required by JPA and for Jackson deserialisation.
     */
    public User() {}

    /**
     * Returns the unique database identifier of this user.
     *
     * @return the user ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique database identifier of this user.
     *
     * @param id the user ID to set
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the full display name of this user.
     *
     * @return the user's display name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the full display name of this user.
     *
     * @param name the display name to set; must not be blank
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the unique email address used as this user's login identifier.
     *
     * @return the user's email address
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the unique email address for this user.
     *
     * @param email the email address to set; must be unique across all users
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the BCrypt-encoded password for this user's account.
     *
     * @return the encoded password string (never the plain-text original)
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the BCrypt-encoded password for this user's account.
     *
     * <p>The caller is responsible for encoding the password before passing it here.
     * Plain-text passwords must never be stored directly.</p>
     *
     * @param password the BCrypt-encoded password to set
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns whether this user account is enabled and permitted to authenticate.
     *
     * @return {@code true} if the account is active; {@code false} if disabled
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the enabled status of this user account.
     *
     * @param enabled {@code true} to activate; {@code false} to disable
     */
    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Returns whether this user account is locked.
     *
     * @return {@code true} if the account is locked and cannot log in;
     *         {@code false} if access is permitted
     */
    public boolean isAccountLocked() {
        return accountLocked;
    }

    /**
     * Sets the locked status of this user account.
     *
     * @param accountLocked {@code true} to lock the account; {@code false} to unlock it
     */
    public void setAccountLocked(boolean accountLocked) {
        this.accountLocked = accountLocked;
    }

    /**
     * Returns the list of expense records owned by this user.
     *
     * @return a list of {@link Expense} entities; may be empty
     */
    public List<Expense> getExpenses() {
        return expenses;
    }

    /**
     * Sets the list of expense records owned by this user.
     *
     * @param expenses the list of {@link Expense} entities to associate
     */
    public void setExpenses(List<Expense> expenses) {
        this.expenses = expenses;
    }
}
